#------------------------------------------------------------------------------
# SPP-Solver — A compact Set Packing solver blending MILP, heuristics,
#              and efficient BitVector techniques.
#------------------------------------------------------------------------------
# Copyright (c) 2026 Josué Tambwe
#               Nantes Université, France
#------------------------------------------------------------------------------
# This software is released under the MIT License.
# See the LICENSE file for more details.
#------------------------------------------------------------------------------


# all source files of the output subdirectory 
output_sources = files('Logger.cpp', 
                       'GeneralOutput.cpp',
                       'GreedyOutput.cpp',
                       'BranchAndBoundOutput.cpp',
                       'MilpSolverOutput.cpp',
                       'GRASPOutput.cpp',
                       'TabuSearchOutput.cpp')