#------------------------------------------------------------------------------
# SPP-Solver — A compact Set Packing solver blending MILP, heuristics,
#              and efficient BitVector techniques.
#------------------------------------------------------------------------------
# Copyright (c) 2026 Josué Tambwe
#               Nantes Université, France
#------------------------------------------------------------------------------
# This software is released under the MIT License.
# See the LICENSE file for more details.
#------------------------------------------------------------------------------


# all source files of the solver subdirectory 
data_struc_sources = files('Instance.cpp',
                           'Parameters.cpp',
                           'Status.cpp',
                           'BitVector.cpp',
                           'Solution.cpp')