#------------------------------------------------------------------------------
# SPP-Solver — A compact Set Packing solver blending MILP, heuristics,
#              and efficient BitVector techniques.
#------------------------------------------------------------------------------
# Copyright (c) 2026 Josué Tambwe
#               Nantes Université, France
#------------------------------------------------------------------------------
# This software is released under the MIT License.
# See the LICENSE file for more details.
#------------------------------------------------------------------------------


# all source files of the grasp subdirectory 
grasp_sources = files('ReactiveGRASP.cpp',
                      'RunGRASP.cpp',
                      'GRASPUtils.cpp',
                      'PathRelinking.cpp')